### ISSUE TITLE
Expected integer for top but received NaN of type number

### ISSUE THREAD

**Issue by bluewave41** [ssnangua/sharp-gif2#2]
```
const fs = require("fs");
const sharp = require("sharp");
const GIF = require("sharp-gif2");

async function process() {
    const reader = GIF.readGif(sharp("./bulbasaur.gif", { anmiated: true }));
    const frames = await reader.toFrames();
}

process();
```

![bulbasaur](https://user-images.githubusercontent.com/9813994/216792953-fbd1edd8-b383-4616-8ff8-e861b419e0f7.gif)

**Comment by ssnangua** [comment]
> ```
> const fs = require("fs");
> const sharp = require("sharp");
> const GIF = require("sharp-gif2");
> 
> async function process() {
>     const reader = GIF.readGif(sharp("./bulbasaur.gif", { anmiated: true }));
>     const frames = await reader.toFrames();
> }
> 
> process();
> ```
> 
> ![bulbasaur](https://user-images.githubusercontent.com/9813994/216792953-fbd1edd8-b383-4616-8ff8-e861b419e0f7.gif)

Maybe you made a mistake here：

```javascript
//                                                "animated", not "anmiated"
//                                                            ↓
    const reader = GIF.readGif(sharp("./bulbasaur.gif", { anmiated: true }));
```
