### ISSUE TITLE
Tips for making animated webp?

### ISSUE THREAD

**Issue by electrovir** [ssnangua/sharp-gif2#3]
I'm curious if you have any tips on making animated webp files? I've searched around npm for a direct "multiple webp images" -> "animated webp image" package, but this is the best I've found so far. However, the intermediate conversion into a gif reduces quality substantially (at least with the default settings).

Any tips on either:
1. using this library to created animated webp images from an array of webp images without losing quality or
2. finding or making my own package similar to this one that doesn't convert to a gif in the middle of the webps -> animated webp conversion.

Regardless, at least I've got a prototype up and running using this package. Thanks!

**Comment by ssnangua** [comment]
Maybe you can try [node-webpmux](https://github.com/ApeironTsuka/node-webpmux):

```javascript
const WebP = require("node-webpmux");

(async () => {
  let img = new WebP.Image();
  await img.load(`./frames/0000.webp`);
  img.convertToAnim();
  for (let i = 0, frameCount = 6; i < frameCount; i++) {
    img.frames[i] = await WebP.Image.generateFrame({
      path: `./frames/000${i}.webp`,
    });
  }
  img.save("./animated.webp");
})();

```

---

Or [webp-converter](https://github.com/scionoftech/webp-converter#create-an-animated-webp-file-from-webp-images):

```javascript
const webp = require("webp-converter");

let input = [
  { path: "./frames/0000.webp", offset: "+100" },
  { path: "./frames/0001.webp", offset: "+100" },
  { path: "./frames/0002.webp", offset: "+100" },
];
webp.webpmux_animate(input, "./animated2.webp", "0", "255,255,255,255", "");

```

**Comment by electrovir** [comment]
Thanks for the tips!

I just tried out `node-webpmux` and it somehow produced worse looking outputs! I'm not sure why. After playing with its settings for ages, I'm giving up and sticking with sharp-gif2, despite losing some color range.

(`webp-converter` is deprecated and contains known vulnerabilities)

Thanks for this great library!
